#standardSQL
SELECT
  MIN(Date) AS Date,
  Year AS Year,
  Month AS Month,
  AVG(DelayMin) AS DelayMin,
  AVG(DelayMax) AS DelayMax,
  COUNT(qid) as QuestionCount,
  SUM(IF(Answers > 0, 1, 0)) / COUNT(*) AS AnswerRate,
  SUM(IF(OneDay, 1, 0)) / COUNT(*) AS OneDayAnswerRate,
  SUM(IF(OneWeek, 1, 0)) / COUNT(*) AS OneWeekAnswerRate,
  
  
  #Java
  SUM(IF(Java > 0, 1, 0)) AS JavaQuestionCount,
  IF(SUM(IF(Java > 0, 1, 0)) = 0, NULL, SUM(IF ((Java > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Java > 0, 1, 0)))  As JavaAnswerRate,
  IF(SUM(IF(Java > 0, 1, 0)) = 0, NULL, SUM(IF ((Java > 0) AND (OneDay), 1, 0)) / SUM(IF(Java > 0, 1, 0)))  As JavaOneDayAnswerRate,
  IF(SUM(IF(Java > 0, 1, 0)) = 0, NULL, SUM(IF ((Java > 0) AND (OneWeek), 1, 0)) / SUM(IF(Java > 0, 1, 0)))  As JavaOneWeekAnswerRate,
  AVG(IF(Java > 0, DelayMin, NULL)) AS JavaDelayMin,
  AVG(IF(Java > 0, DelayMax, NULL)) AS JavaDelayMax,
#Javascript
  SUM(IF(Javascript > 0, 1, 0)) AS JavascriptQuestionCount,
  IF(SUM(IF(Javascript > 0, 1, 0)) = 0, NULL, SUM(IF ((Javascript > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Javascript > 0, 1, 0)))  As JavascriptAnswerRate,
  IF(SUM(IF(Javascript > 0, 1, 0)) = 0, NULL, SUM(IF ((Javascript > 0) AND (OneDay), 1, 0)) / SUM(IF(Javascript > 0, 1, 0)))  As JavascriptOneDayAnswerRate,
  IF(SUM(IF(Javascript > 0, 1, 0)) = 0, NULL, SUM(IF ((Javascript > 0) AND (OneWeek), 1, 0)) / SUM(IF(Javascript > 0, 1, 0)))  As JavascriptOneWeekAnswerRate,
  AVG(IF(Javascript > 0, DelayMin, NULL)) AS JavascriptDelayMin,
  AVG(IF(Javascript > 0, DelayMax, NULL)) AS JavascriptDelayMax,
#Php
  SUM(IF(Php > 0, 1, 0)) AS PhpQuestionCount,
  IF(SUM(IF(Php > 0, 1, 0)) = 0, NULL, SUM(IF ((Php > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Php > 0, 1, 0)))  As PhpAnswerRate,
  IF(SUM(IF(Php > 0, 1, 0)) = 0, NULL, SUM(IF ((Php > 0) AND (OneDay), 1, 0)) / SUM(IF(Php > 0, 1, 0)))  As PhpOneDayAnswerRate,
  IF(SUM(IF(Php > 0, 1, 0)) = 0, NULL, SUM(IF ((Php > 0) AND (OneWeek), 1, 0)) / SUM(IF(Php > 0, 1, 0)))  As PhpOneWeekAnswerRate,
  AVG(IF(Php > 0, DelayMin, NULL)) AS PhpDelayMin,
  AVG(IF(Php > 0, DelayMax, NULL)) AS PhpDelayMax,
#Python
  SUM(IF(Python > 0, 1, 0)) AS PythonQuestionCount,
  IF(SUM(IF(Python > 0, 1, 0)) = 0, NULL, SUM(IF ((Python > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Python > 0, 1, 0)))  As PythonAnswerRate,
  IF(SUM(IF(Python > 0, 1, 0)) = 0, NULL, SUM(IF ((Python > 0) AND (OneDay), 1, 0)) / SUM(IF(Python > 0, 1, 0)))  As PythonOneDayAnswerRate,
  IF(SUM(IF(Python > 0, 1, 0)) = 0, NULL, SUM(IF ((Python > 0) AND (OneWeek), 1, 0)) / SUM(IF(Python > 0, 1, 0)))  As PythonOneWeekAnswerRate,
  AVG(IF(Python > 0, DelayMin, NULL)) AS PythonDelayMin,
  AVG(IF(Python > 0, DelayMax, NULL)) AS PythonDelayMax,
#CSharp
  SUM(IF(CSharp > 0, 1, 0)) AS CSharpQuestionCount,
  IF(SUM(IF(CSharp > 0, 1, 0)) = 0, NULL, SUM(IF ((CSharp > 0) AND (Answers > 0), 1, 0)) / SUM(IF(CSharp > 0, 1, 0)))  As CSharpAnswerRate,
  IF(SUM(IF(CSharp > 0, 1, 0)) = 0, NULL, SUM(IF ((CSharp > 0) AND (OneDay), 1, 0)) / SUM(IF(CSharp > 0, 1, 0)))  As CSharpOneDayAnswerRate,
  IF(SUM(IF(CSharp > 0, 1, 0)) = 0, NULL, SUM(IF ((CSharp > 0) AND (OneWeek), 1, 0)) / SUM(IF(CSharp > 0, 1, 0)))  As CSharpOneWeekAnswerRate,
  AVG(IF(CSharp > 0, DelayMin, NULL)) AS CSharpDelayMin,
  AVG(IF(CSharp > 0, DelayMax, NULL)) AS CSharpDelayMax,
#Cplusplus
  SUM(IF(Cplusplus > 0, 1, 0)) AS CplusplusQuestionCount,
  IF(SUM(IF(Cplusplus > 0, 1, 0)) = 0, NULL, SUM(IF ((Cplusplus > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Cplusplus > 0, 1, 0)))  As CplusplusAnswerRate,
  IF(SUM(IF(Cplusplus > 0, 1, 0)) = 0, NULL, SUM(IF ((Cplusplus > 0) AND (OneDay), 1, 0)) / SUM(IF(Cplusplus > 0, 1, 0)))  As CplusplusOneDayAnswerRate,
  IF(SUM(IF(Cplusplus > 0, 1, 0)) = 0, NULL, SUM(IF ((Cplusplus > 0) AND (OneWeek), 1, 0)) / SUM(IF(Cplusplus > 0, 1, 0)))  As CplusplusOneWeekAnswerRate,
  AVG(IF(Cplusplus > 0, DelayMin, NULL)) AS CplusplusDelayMin,
  AVG(IF(Cplusplus > 0, DelayMax, NULL)) AS CplusplusDelayMax,
#Ruby
  SUM(IF(Ruby > 0, 1, 0)) AS RubyQuestionCount,
  IF(SUM(IF(Ruby > 0, 1, 0)) = 0, NULL, SUM(IF ((Ruby > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Ruby > 0, 1, 0)))  As RubyAnswerRate,
  IF(SUM(IF(Ruby > 0, 1, 0)) = 0, NULL, SUM(IF ((Ruby > 0) AND (OneDay), 1, 0)) / SUM(IF(Ruby > 0, 1, 0)))  As RubyOneDayAnswerRate,
  IF(SUM(IF(Ruby > 0, 1, 0)) = 0, NULL, SUM(IF ((Ruby > 0) AND (OneWeek), 1, 0)) / SUM(IF(Ruby > 0, 1, 0)))  As RubyOneWeekAnswerRate,
  AVG(IF(Ruby > 0, DelayMin, NULL)) AS RubyDelayMin,
  AVG(IF(Ruby > 0, DelayMax, NULL)) AS RubyDelayMax,
#Css
  SUM(IF(Css > 0, 1, 0)) AS CssQuestionCount,
  IF(SUM(IF(Css > 0, 1, 0)) = 0, NULL, SUM(IF ((Css > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Css > 0, 1, 0)))  As CssAnswerRate,
  IF(SUM(IF(Css > 0, 1, 0)) = 0, NULL, SUM(IF ((Css > 0) AND (OneDay), 1, 0)) / SUM(IF(Css > 0, 1, 0)))  As CssOneDayAnswerRate,
  IF(SUM(IF(Css > 0, 1, 0)) = 0, NULL, SUM(IF ((Css > 0) AND (OneWeek), 1, 0)) / SUM(IF(Css > 0, 1, 0)))  As CssOneWeekAnswerRate,
  AVG(IF(Css > 0, DelayMin, NULL)) AS CssDelayMin,
  AVG(IF(Css > 0, DelayMax, NULL)) AS CssDelayMax,
#C
  SUM(IF(C > 0, 1, 0)) AS CQuestionCount,
  IF(SUM(IF(C > 0, 1, 0)) = 0, NULL, SUM(IF ((C > 0) AND (Answers > 0), 1, 0)) / SUM(IF(C > 0, 1, 0)))  As CAnswerRate,
  IF(SUM(IF(C > 0, 1, 0)) = 0, NULL, SUM(IF ((C > 0) AND (OneDay), 1, 0)) / SUM(IF(C > 0, 1, 0)))  As COneDayAnswerRate,
  IF(SUM(IF(C > 0, 1, 0)) = 0, NULL, SUM(IF ((C > 0) AND (OneWeek), 1, 0)) / SUM(IF(C > 0, 1, 0)))  As COneWeekAnswerRate,
  AVG(IF(C > 0, DelayMin, NULL)) AS CDelayMin,
  AVG(IF(C > 0, DelayMax, NULL)) AS CDelayMax,
#ObjectiveC
  SUM(IF(ObjectiveC > 0, 1, 0)) AS ObjectiveCQuestionCount,
  IF(SUM(IF(ObjectiveC > 0, 1, 0)) = 0, NULL, SUM(IF ((ObjectiveC > 0) AND (Answers > 0), 1, 0)) / SUM(IF(ObjectiveC > 0, 1, 0)))  As ObjectiveCAnswerRate,
  IF(SUM(IF(ObjectiveC > 0, 1, 0)) = 0, NULL, SUM(IF ((ObjectiveC > 0) AND (OneDay), 1, 0)) / SUM(IF(ObjectiveC > 0, 1, 0)))  As ObjectiveCOneDayAnswerRate,
  IF(SUM(IF(ObjectiveC > 0, 1, 0)) = 0, NULL, SUM(IF ((ObjectiveC > 0) AND (OneWeek), 1, 0)) / SUM(IF(ObjectiveC > 0, 1, 0)))  As ObjectiveCOneWeekAnswerRate,
  AVG(IF(ObjectiveC > 0, DelayMin, NULL)) AS ObjectiveCDelayMin,
  AVG(IF(ObjectiveC > 0, DelayMax, NULL)) AS ObjectiveCDelayMax,
#Shell
  SUM(IF(Shell > 0, 1, 0)) AS ShellQuestionCount,
  IF(SUM(IF(Shell > 0, 1, 0)) = 0, NULL, SUM(IF ((Shell > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Shell > 0, 1, 0)))  As ShellAnswerRate,
  IF(SUM(IF(Shell > 0, 1, 0)) = 0, NULL, SUM(IF ((Shell > 0) AND (OneDay), 1, 0)) / SUM(IF(Shell > 0, 1, 0)))  As ShellOneDayAnswerRate,
  IF(SUM(IF(Shell > 0, 1, 0)) = 0, NULL, SUM(IF ((Shell > 0) AND (OneWeek), 1, 0)) / SUM(IF(Shell > 0, 1, 0)))  As ShellOneWeekAnswerRate,
  AVG(IF(Shell > 0, DelayMin, NULL)) AS ShellDelayMin,
  AVG(IF(Shell > 0, DelayMax, NULL)) AS ShellDelayMax,
#R
  SUM(IF(R > 0, 1, 0)) AS RQuestionCount,
  IF(SUM(IF(R > 0, 1, 0)) = 0, NULL, SUM(IF ((R > 0) AND (Answers > 0), 1, 0)) / SUM(IF(R > 0, 1, 0)))  As RAnswerRate,
  IF(SUM(IF(R > 0, 1, 0)) = 0, NULL, SUM(IF ((R > 0) AND (OneDay), 1, 0)) / SUM(IF(R > 0, 1, 0)))  As ROneDayAnswerRate,
  IF(SUM(IF(R > 0, 1, 0)) = 0, NULL, SUM(IF ((R > 0) AND (OneWeek), 1, 0)) / SUM(IF(R > 0, 1, 0)))  As ROneWeekAnswerRate,
  AVG(IF(R > 0, DelayMin, NULL)) AS RDelayMin,
  AVG(IF(R > 0, DelayMax, NULL)) AS RDelayMax,
#Perl
  SUM(IF(Perl > 0, 1, 0)) AS PerlQuestionCount,
  IF(SUM(IF(Perl > 0, 1, 0)) = 0, NULL, SUM(IF ((Perl > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Perl > 0, 1, 0)))  As PerlAnswerRate,
  IF(SUM(IF(Perl > 0, 1, 0)) = 0, NULL, SUM(IF ((Perl > 0) AND (OneDay), 1, 0)) / SUM(IF(Perl > 0, 1, 0)))  As PerlOneDayAnswerRate,
  IF(SUM(IF(Perl > 0, 1, 0)) = 0, NULL, SUM(IF ((Perl > 0) AND (OneWeek), 1, 0)) / SUM(IF(Perl > 0, 1, 0)))  As PerlOneWeekAnswerRate,
  AVG(IF(Perl > 0, DelayMin, NULL)) AS PerlDelayMin,
  AVG(IF(Perl > 0, DelayMax, NULL)) AS PerlDelayMax,
#Scala
  SUM(IF(Scala > 0, 1, 0)) AS ScalaQuestionCount,
  IF(SUM(IF(Scala > 0, 1, 0)) = 0, NULL, SUM(IF ((Scala > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Scala > 0, 1, 0)))  As ScalaAnswerRate,
  IF(SUM(IF(Scala > 0, 1, 0)) = 0, NULL, SUM(IF ((Scala > 0) AND (OneDay), 1, 0)) / SUM(IF(Scala > 0, 1, 0)))  As ScalaOneDayAnswerRate,
  IF(SUM(IF(Scala > 0, 1, 0)) = 0, NULL, SUM(IF ((Scala > 0) AND (OneWeek), 1, 0)) / SUM(IF(Scala > 0, 1, 0)))  As ScalaOneWeekAnswerRate,
  AVG(IF(Scala > 0, DelayMin, NULL)) AS ScalaDelayMin,
  AVG(IF(Scala > 0, DelayMax, NULL)) AS ScalaDelayMax,
#Go
  SUM(IF(Go > 0, 1, 0)) AS GoQuestionCount,
  IF(SUM(IF(Go > 0, 1, 0)) = 0, NULL, SUM(IF ((Go > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Go > 0, 1, 0)))  As GoAnswerRate,
  IF(SUM(IF(Go > 0, 1, 0)) = 0, NULL, SUM(IF ((Go > 0) AND (OneDay), 1, 0)) / SUM(IF(Go > 0, 1, 0)))  As GoOneDayAnswerRate,
  IF(SUM(IF(Go > 0, 1, 0)) = 0, NULL, SUM(IF ((Go > 0) AND (OneWeek), 1, 0)) / SUM(IF(Go > 0, 1, 0)))  As GoOneWeekAnswerRate,
  AVG(IF(Go > 0, DelayMin, NULL)) AS GoDelayMin,
  AVG(IF(Go > 0, DelayMax, NULL)) AS GoDelayMax,
#Haskell
  SUM(IF(Haskell > 0, 1, 0)) AS HaskellQuestionCount,
  IF(SUM(IF(Haskell > 0, 1, 0)) = 0, NULL, SUM(IF ((Haskell > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Haskell > 0, 1, 0)))  As HaskellAnswerRate,
  IF(SUM(IF(Haskell > 0, 1, 0)) = 0, NULL, SUM(IF ((Haskell > 0) AND (OneDay), 1, 0)) / SUM(IF(Haskell > 0, 1, 0)))  As HaskellOneDayAnswerRate,
  IF(SUM(IF(Haskell > 0, 1, 0)) = 0, NULL, SUM(IF ((Haskell > 0) AND (OneWeek), 1, 0)) / SUM(IF(Haskell > 0, 1, 0)))  As HaskellOneWeekAnswerRate,
  AVG(IF(Haskell > 0, DelayMin, NULL)) AS HaskellDelayMin,
  AVG(IF(Haskell > 0, DelayMax, NULL)) AS HaskellDelayMax,
#Swift
  SUM(IF(Swift > 0, 1, 0)) AS SwiftQuestionCount,
  IF(SUM(IF(Swift > 0, 1, 0)) = 0, NULL, SUM(IF ((Swift > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Swift > 0, 1, 0)))  As SwiftAnswerRate,
  IF(SUM(IF(Swift > 0, 1, 0)) = 0, NULL, SUM(IF ((Swift > 0) AND (OneDay), 1, 0)) / SUM(IF(Swift > 0, 1, 0)))  As SwiftOneDayAnswerRate,
  IF(SUM(IF(Swift > 0, 1, 0)) = 0, NULL, SUM(IF ((Swift > 0) AND (OneWeek), 1, 0)) / SUM(IF(Swift > 0, 1, 0)))  As SwiftOneWeekAnswerRate,
  AVG(IF(Swift > 0, DelayMin, NULL)) AS SwiftDelayMin,
  AVG(IF(Swift > 0, DelayMax, NULL)) AS SwiftDelayMax,
#Matlab
  SUM(IF(Matlab > 0, 1, 0)) AS MatlabQuestionCount,
  IF(SUM(IF(Matlab > 0, 1, 0)) = 0, NULL, SUM(IF ((Matlab > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Matlab > 0, 1, 0)))  As MatlabAnswerRate,
  IF(SUM(IF(Matlab > 0, 1, 0)) = 0, NULL, SUM(IF ((Matlab > 0) AND (OneDay), 1, 0)) / SUM(IF(Matlab > 0, 1, 0)))  As MatlabOneDayAnswerRate,
  IF(SUM(IF(Matlab > 0, 1, 0)) = 0, NULL, SUM(IF ((Matlab > 0) AND (OneWeek), 1, 0)) / SUM(IF(Matlab > 0, 1, 0)))  As MatlabOneWeekAnswerRate,
  AVG(IF(Matlab > 0, DelayMin, NULL)) AS MatlabDelayMin,
  AVG(IF(Matlab > 0, DelayMax, NULL)) AS MatlabDelayMax,
#Clojure
  SUM(IF(Clojure > 0, 1, 0)) AS ClojureQuestionCount,
  IF(SUM(IF(Clojure > 0, 1, 0)) = 0, NULL, SUM(IF ((Clojure > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Clojure > 0, 1, 0)))  As ClojureAnswerRate,
  IF(SUM(IF(Clojure > 0, 1, 0)) = 0, NULL, SUM(IF ((Clojure > 0) AND (OneDay), 1, 0)) / SUM(IF(Clojure > 0, 1, 0)))  As ClojureOneDayAnswerRate,
  IF(SUM(IF(Clojure > 0, 1, 0)) = 0, NULL, SUM(IF ((Clojure > 0) AND (OneWeek), 1, 0)) / SUM(IF(Clojure > 0, 1, 0)))  As ClojureOneWeekAnswerRate,
  AVG(IF(Clojure > 0, DelayMin, NULL)) AS ClojureDelayMin,
  AVG(IF(Clojure > 0, DelayMax, NULL)) AS ClojureDelayMax,
#Groovy
  SUM(IF(Groovy > 0, 1, 0)) AS GroovyQuestionCount,
  IF(SUM(IF(Groovy > 0, 1, 0)) = 0, NULL, SUM(IF ((Groovy > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Groovy > 0, 1, 0)))  As GroovyAnswerRate,
  IF(SUM(IF(Groovy > 0, 1, 0)) = 0, NULL, SUM(IF ((Groovy > 0) AND (OneDay), 1, 0)) / SUM(IF(Groovy > 0, 1, 0)))  As GroovyOneDayAnswerRate,
  IF(SUM(IF(Groovy > 0, 1, 0)) = 0, NULL, SUM(IF ((Groovy > 0) AND (OneWeek), 1, 0)) / SUM(IF(Groovy > 0, 1, 0)))  As GroovyOneWeekAnswerRate,
  AVG(IF(Groovy > 0, DelayMin, NULL)) AS GroovyDelayMin,
  AVG(IF(Groovy > 0, DelayMax, NULL)) AS GroovyDelayMax,
#AEM
  SUM(IF(AEM > 0, 1, 0)) AS AEMQuestionCount,
  IF(SUM(IF(AEM > 0, 1, 0)) = 0, NULL, SUM(IF ((AEM > 0) AND (Answers > 0), 1, 0)) / SUM(IF(AEM > 0, 1, 0)))  As AEMAnswerRate,
  IF(SUM(IF(AEM > 0, 1, 0)) = 0, NULL, SUM(IF ((AEM > 0) AND (OneDay), 1, 0)) / SUM(IF(AEM > 0, 1, 0)))  As AEMOneDayAnswerRate,
  IF(SUM(IF(AEM > 0, 1, 0)) = 0, NULL, SUM(IF ((AEM > 0) AND (OneWeek), 1, 0)) / SUM(IF(AEM > 0, 1, 0)))  As AEMOneWeekAnswerRate,
  AVG(IF(AEM > 0, DelayMin, NULL)) AS AEMDelayMin,
  AVG(IF(AEM > 0, DelayMax, NULL)) AS AEMDelayMax,
#PDF
  SUM(IF(PDF > 0, 1, 0)) AS PDFQuestionCount,
  IF(SUM(IF(PDF > 0, 1, 0)) = 0, NULL, SUM(IF ((PDF > 0) AND (Answers > 0), 1, 0)) / SUM(IF(PDF > 0, 1, 0)))  As PDFAnswerRate,
  IF(SUM(IF(PDF > 0, 1, 0)) = 0, NULL, SUM(IF ((PDF > 0) AND (OneDay), 1, 0)) / SUM(IF(PDF > 0, 1, 0)))  As PDFOneDayAnswerRate,
  IF(SUM(IF(PDF > 0, 1, 0)) = 0, NULL, SUM(IF ((PDF > 0) AND (OneWeek), 1, 0)) / SUM(IF(PDF > 0, 1, 0)))  As PDFOneWeekAnswerRate,
  AVG(IF(PDF > 0, DelayMin, NULL)) AS PDFDelayMin,
  AVG(IF(PDF > 0, DelayMax, NULL)) AS PDFDelayMax,
#Adobe
  SUM(IF(Adobe > 0, 1, 0)) AS AdobeQuestionCount,
  IF(SUM(IF(Adobe > 0, 1, 0)) = 0, NULL, SUM(IF ((Adobe > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Adobe > 0, 1, 0)))  As AdobeAnswerRate,
  IF(SUM(IF(Adobe > 0, 1, 0)) = 0, NULL, SUM(IF ((Adobe > 0) AND (OneDay), 1, 0)) / SUM(IF(Adobe > 0, 1, 0)))  As AdobeOneDayAnswerRate,
  IF(SUM(IF(Adobe > 0, 1, 0)) = 0, NULL, SUM(IF ((Adobe > 0) AND (OneWeek), 1, 0)) / SUM(IF(Adobe > 0, 1, 0)))  As AdobeOneWeekAnswerRate,
  AVG(IF(Adobe > 0, DelayMin, NULL)) AS AdobeDelayMin,
  AVG(IF(Adobe > 0, DelayMax, NULL)) AS AdobeDelayMax,
#Phonegap
  SUM(IF(Phonegap > 0, 1, 0)) AS PhonegapQuestionCount,
  IF(SUM(IF(Phonegap > 0, 1, 0)) = 0, NULL, SUM(IF ((Phonegap > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Phonegap > 0, 1, 0)))  As PhonegapAnswerRate,
  IF(SUM(IF(Phonegap > 0, 1, 0)) = 0, NULL, SUM(IF ((Phonegap > 0) AND (OneDay), 1, 0)) / SUM(IF(Phonegap > 0, 1, 0)))  As PhonegapOneDayAnswerRate,
  IF(SUM(IF(Phonegap > 0, 1, 0)) = 0, NULL, SUM(IF ((Phonegap > 0) AND (OneWeek), 1, 0)) / SUM(IF(Phonegap > 0, 1, 0)))  As PhonegapOneWeekAnswerRate,
  AVG(IF(Phonegap > 0, DelayMin, NULL)) AS PhonegapDelayMin,
  AVG(IF(Phonegap > 0, DelayMax, NULL)) AS PhonegapDelayMax,
#Flash
  SUM(IF(Flash > 0, 1, 0)) AS FlashQuestionCount,
  IF(SUM(IF(Flash > 0, 1, 0)) = 0, NULL, SUM(IF ((Flash > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Flash > 0, 1, 0)))  As FlashAnswerRate,
  IF(SUM(IF(Flash > 0, 1, 0)) = 0, NULL, SUM(IF ((Flash > 0) AND (OneDay), 1, 0)) / SUM(IF(Flash > 0, 1, 0)))  As FlashOneDayAnswerRate,
  IF(SUM(IF(Flash > 0, 1, 0)) = 0, NULL, SUM(IF ((Flash > 0) AND (OneWeek), 1, 0)) / SUM(IF(Flash > 0, 1, 0)))  As FlashOneWeekAnswerRate,
  AVG(IF(Flash > 0, DelayMin, NULL)) AS FlashDelayMin,
  AVG(IF(Flash > 0, DelayMax, NULL)) AS FlashDelayMax,
#Photoshop
  SUM(IF(Photoshop > 0, 1, 0)) AS PhotoshopQuestionCount,
  IF(SUM(IF(Photoshop > 0, 1, 0)) = 0, NULL, SUM(IF ((Photoshop > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Photoshop > 0, 1, 0)))  As PhotoshopAnswerRate,
  IF(SUM(IF(Photoshop > 0, 1, 0)) = 0, NULL, SUM(IF ((Photoshop > 0) AND (OneDay), 1, 0)) / SUM(IF(Photoshop > 0, 1, 0)))  As PhotoshopOneDayAnswerRate,
  IF(SUM(IF(Photoshop > 0, 1, 0)) = 0, NULL, SUM(IF ((Photoshop > 0) AND (OneWeek), 1, 0)) / SUM(IF(Photoshop > 0, 1, 0)))  As PhotoshopOneWeekAnswerRate,
  AVG(IF(Photoshop > 0, DelayMin, NULL)) AS PhotoshopDelayMin,
  AVG(IF(Photoshop > 0, DelayMax, NULL)) AS PhotoshopDelayMax,
#Actionscript
  SUM(IF(Actionscript > 0, 1, 0)) AS ActionscriptQuestionCount,
  IF(SUM(IF(Actionscript > 0, 1, 0)) = 0, NULL, SUM(IF ((Actionscript > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Actionscript > 0, 1, 0)))  As ActionscriptAnswerRate,
  IF(SUM(IF(Actionscript > 0, 1, 0)) = 0, NULL, SUM(IF ((Actionscript > 0) AND (OneDay), 1, 0)) / SUM(IF(Actionscript > 0, 1, 0)))  As ActionscriptOneDayAnswerRate,
  IF(SUM(IF(Actionscript > 0, 1, 0)) = 0, NULL, SUM(IF ((Actionscript > 0) AND (OneWeek), 1, 0)) / SUM(IF(Actionscript > 0, 1, 0)))  As ActionscriptOneWeekAnswerRate,
  AVG(IF(Actionscript > 0, DelayMin, NULL)) AS ActionscriptDelayMin,
  AVG(IF(Actionscript > 0, DelayMax, NULL)) AS ActionscriptDelayMax,
#Coldfusion
  SUM(IF(Coldfusion > 0, 1, 0)) AS ColdfusionQuestionCount,
  IF(SUM(IF(Coldfusion > 0, 1, 0)) = 0, NULL, SUM(IF ((Coldfusion > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Coldfusion > 0, 1, 0)))  As ColdfusionAnswerRate,
  IF(SUM(IF(Coldfusion > 0, 1, 0)) = 0, NULL, SUM(IF ((Coldfusion > 0) AND (OneDay), 1, 0)) / SUM(IF(Coldfusion > 0, 1, 0)))  As ColdfusionOneDayAnswerRate,
  IF(SUM(IF(Coldfusion > 0, 1, 0)) = 0, NULL, SUM(IF ((Coldfusion > 0) AND (OneWeek), 1, 0)) / SUM(IF(Coldfusion > 0, 1, 0)))  As ColdfusionOneWeekAnswerRate,
  AVG(IF(Coldfusion > 0, DelayMin, NULL)) AS ColdfusionDelayMin,
  AVG(IF(Coldfusion > 0, DelayMax, NULL)) AS ColdfusionDelayMax,
#Xmp
  SUM(IF(Xmp > 0, 1, 0)) AS XmpQuestionCount,
  IF(SUM(IF(Xmp > 0, 1, 0)) = 0, NULL, SUM(IF ((Xmp > 0) AND (Answers > 0), 1, 0)) / SUM(IF(Xmp > 0, 1, 0)))  As XmpAnswerRate,
  IF(SUM(IF(Xmp > 0, 1, 0)) = 0, NULL, SUM(IF ((Xmp > 0) AND (OneDay), 1, 0)) / SUM(IF(Xmp > 0, 1, 0)))  As XmpOneDayAnswerRate,
  IF(SUM(IF(Xmp > 0, 1, 0)) = 0, NULL, SUM(IF ((Xmp > 0) AND (OneWeek), 1, 0)) / SUM(IF(Xmp > 0, 1, 0)))  As XmpOneWeekAnswerRate,
  AVG(IF(Xmp > 0, DelayMin, NULL)) AS XmpDelayMin,
  AVG(IF(Xmp > 0, DelayMax, NULL)) AS XmpDelayMax
  
  
  
  #IF(XLANGX > 0, TRUE, FALSE) AS Java
FROM
  test.soquestions
GROUP BY
  Year, Month
HAVING
Year > 2009